name: reviewdog
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/checkout@v2

      - name: Setup reviewdog
        run: |
          make bootstrap-lint-tools
          echo ::add-path::$(go env GOPATH)/bin # for Go projects
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            reviewdog -reporter=github-pr-check -runners=govet,golint
